### ISSUE TITLE
the definition of F as a set of sets sounds incorrect

### ISSUE THREAD

**Issue by adl** [adl/hoaf#48]
In the [formal semantics](http://adl.github.io/hoaf/#formal-semantics-of-omega-automata) we have something like this

> $F=\{S_0,S_1,…,S_{m−1}\}$ is a finite set of acceptance sets. 

where each S_i is a subset of transitions.

I think declaring F as a set is a mistake, because it implicitly implies that all S_i will be different, which is not the case in the format.

I suggest to rewrite this as

> $F=(S_0,S_1,…,S_{m−1})$ is a tuple of $m$ acceptance sets. 

Do you agree?

**Comment by xblahoud** [comment]
Tuple sounds fine to me. It naturally comes with the order and indexing the sets. I can't see any advantage of having a set there.

**Comment by strejcek** [comment]
Or we can say that $F=S_0,S_1,…,S_{m−1}$ is a finite sequence of $m$ acceptance sets.
I like it slightly more than tuples of an arbitrary arity/length.
