### ISSUE TITLE
HOA logo

### ISSUE THREAD

**Issue by adl** [adl/hoaf#51]
Joachim, Jan S. and I have been discussing logos over the past month.  This is the current runner up.  It's based on an original idea by Jan, rendered [in TikZ](https://gist.github.com/adl/40390ec9fb296d5dbf1c) by me, and including some adjustments from Joachim.  I've just recently added an "horizontal" bar to the H, and prepared a small version that can be used as an icon (for file organizers).

Full version:
![hoa-full](https://cloud.githubusercontent.com/assets/822900/8881922/a1c188c6-3243-11e5-9fee-b4d874f9305c.png)

Icon version
![hoa-icon](https://cloud.githubusercontent.com/assets/822900/8881925/a6e4872c-3243-11e5-9240-9b47bccb862a.png)

What do you think?

**Comment by kleinj** [comment]
Thanks, I like it. The magenta color for the O is a bit strong, I'd prefer a different color scheme. I like the addition of the H middle bar. It's probably not possible to add something similar to the A, perhaps with a down swing to get symmetry?

For the icon version I think that the state in the O is too large, at low magnification (think favicon) there is not enough separation. Shrinking the state (and adapting the arrows) might make it work better.

**Comment by JanKretinsky** [comment]
Hi,

2015-07-24 13:56 GMT-07:00 Joachim Klein <notifications@github.com>:

> Thanks, I like it. The magenta color for the O is a bit strong, I'd prefer
> a different color scheme. I like the addition of the H middle bar. It's
> probably not possible to add something similar to the A, perhaps with a
> down swing to get symmetry?
>
> For the icon version I think that the state in the O is too large, at low
> magnification (think favicon) there is not enough separation. Shrinking the
> state (and adapting the arrows) might make it work better.
>

I agree with this second comment
Cheers, J.

**Comment by davexparker** [comment]
Looks great! Although I'm not sure why you showed us the runner up, rather than the winner? ;)

Agreeing with some of the other comments above, it might be good if (i) the H and A were symmetric in terms of whether they have a horizontal bar; and (ii) the icon version looked clearer when reduced in size.

Dave.

**Comment by adl** [comment]
Here is a full logo with a bar to the A (I tried to make it go around the black arrow as for the H, but could not get a satisfying result).  The H is also slightly wider:
![hoa](https://cloud.githubusercontent.com/assets/822900/9108587/977faf3c-3c2f-11e5-855f-c3705d30fa90.png)

Here is the icon with more space between the black and purple circles:
![hoa-icon](https://cloud.githubusercontent.com/assets/822900/9108585/977daa5c-3c2f-11e5-954a-7d244f37da82.png) ![hoa-icon-small](https://cloud.githubusercontent.com/assets/822900/9108586/977def4e-3c2f-11e5-889d-bc505b5dc3d1.png)

**Comment by strejcek** [comment]
I like it. I would prefer only one colour (the blue one) besides black and white. 

I've also put down another variation on the original logo idea (sorry or low quality, I've just 
draw it on a paper, scan it and process it a bit: letters should be regular, arrows and the circle
should be hand-written-like): 

![hoa](https://cloud.githubusercontent.com/assets/6370586/9134537/4570b69c-3d05-11e5-9388-794eb731683f.png)

**Comment by adl** [comment]
Here are the versions with a single color for comparison.
![hoa](https://cloud.githubusercontent.com/assets/822900/9335860/cf588cf2-45d6-11e5-95eb-e406b39a45c1.png) ![hoa-icon](https://cloud.githubusercontent.com/assets/822900/9335859/cf56910e-45d6-11e5-807d-e65e5c3d5ccb.png) ![hoa-icon-small](https://cloud.githubusercontent.com/assets/822900/9335861/cf5bc098-45d6-11e5-8815-accc463a97a9.png)

**Comment by kleinj** [comment]
Thanks, Alexandre. I like the changes you did to the A. I prefer the "all blue" version.
The sketch by Jan looks like a good concept as well. So many options... :)

**Comment by JanKretinsky** [comment]
I also like the simpler blue version a bit more

**Comment by xblahoud** [comment]
I like the version with both A and H havin the bar visible. Regarding the colors, I don't mind either, but slightly prefer the one with more colors. The thick version by Jan S. also looks good.
