### ISSUE TITLE
fixing the semantic of the deterministic property

### ISSUE THREAD

**Issue by adl** [adl/hoaf#63]
Here is a picture of the class of alternating automata, containing dual the subclasses of existential automata (a.k.a. non-deterministic automata) and universal automata.
![alt](https://cloud.githubusercontent.com/assets/822900/22459231/0eac0f20-e7a0-11e6-87b2-997d6ad8d90d.png)

Currently, HOA v1 uses `no-univ-branch` to indicate *existential automata*, and `deterministic` to indicate *universal automata*.  This is unfortunate, because it makes `no-univ-branch` the dual of `deterministic`.

Since we have already renamed `no-univ-branch` into `!univ-branch`, I would like to propose that we rename the actual `deterministic` property as `!exist-branch`, and that we define `deterministic` as syntactic-sugar for `!univ-branch !exist-branch`.

For tools that only work with automata without universal branching, this does not change the semantic of `deterministic`.  The change of semantic of `deterministic` only matters to tools working with alternating automata, but I don't think any of them used `deterministic`  (at least [`ltl3ba -H1`](https://sourceforge.net/projects/ltl3ba/) and [`ltl3dra -H1`](https://sourceforge.net/projects/ltl3dra/) never seems to output `deterministic`).  

[Spot 2.3](https://spot.lrde.epita.fr/hoa.html#property-bits) uses `deterministic` in the specified sense for alternating automata, but I'd really like to change that as suggested, to get in line with existing literature.  In particular when complementing an automaton by dualization (See for instance [Section 1.6 of Löding's Diploma Thesis](http://old.automata.rwth-aachen.de/users/loeding/diploma_loeding.pdf)), I'd really like that an `exist-branch !univ-branch` automaton becomes a `!exist-branch univ-branch` automaton.

**Comment by strejcek** [comment]
I agree with the suggestion.
