### ISSUE TITLE
Not clear whether acceptance sets can be specified both on a set and some of its exit arcs

### ISSUE THREAD

**Issue by vkhomenko** [adl/hoaf#69]
The documentation says:

<code>
The INT* used in acc-sig represent the acceptance sets the state or edge belongs to. Since we use transition-based acceptance, when acc-sig is used on a state to declare membership to some acceptance sets, it is syntactic sugar for the membership of all the outgoing transitions to this set. For instance State: 0 {1 3} would states that all transitions leaving state 0 are in acceptance sets 1 and 3.
</code>

It is not clear whether acc-sig can be specified on both the state and some of its exit arcs. There are several possibilities:
  * disallow this (and explicitly tell in the documentation)
  * allow this and then acc-sig on the state is united with those on the arcs; also, one may require the union to be disjoint.

**Comment by xblahoud** [comment]
This is addressed by the last example among nondeterministic automata where we explicitly allow this and specify this as union of the marks.

**Comment by adl** [comment]
I'm added a not above this in the aforementioned paragraph.

**Comment by strejcek** [comment]
I've just fixed an old typo in the paragraph...
